name: flutter_secure_storage_x_root
repository: https://github.com/koji-1009/flutter_secure_storage

environment:
  sdk: '>=3.9.0 <4.0.0'

workspace:
  - flutter_secure_storage_x
  - flutter_secure_storage_x/example
  - flutter_secure_storage_x_linux
  - flutter_secure_storage_x_macos
  - flutter_secure_storage_x_platform_interface
  - flutter_secure_storage_x_web
  - flutter_secure_storage_x_windows
  - flutter_secure_storage_x_windows/example

dev_dependencies:
  flutter_lints: ^6.0.0
  melos: ^7.0.0

melos:
  command:
    bootstrap:
      environment:
        sdk: '>=3.9.0 <4.0.0'
        flutter: '>=3.35.0'
      dependencies:
        ffi: ^2.0.0
        path: ^1.8.0
        path_provider: ^2.0.0
        web: ^1.0.0
        win32: ^5.5.1
      dev_dependencies:
        flutter_lints: ^6.0.0
